// flow-typed signature: 06f701f4a06719064dbfb583adce0050
// flow-typed version: <<STUB>>/babel-preset-es2015-native-modules_v^6.9.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-native-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-native-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-native-modules/index' {
  declare module.exports: $Exports<'babel-preset-es2015-native-modules'>;
}
declare module 'babel-preset-es2015-native-modules/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-native-modules'>;
}
